using System.Collections.Generic;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;

namespace Gridsum.DataflowEx.Databases
{
    using System;

    /// <summary>
    /// The class helps you to bulk insert parsed objects to the database. 
    /// </summary>
    /// <typeparam name="T">The db-mapped type of parsed objects (usually generated by EF/linq2sql)</typeparam>
    public class DbBulkInserter<T> : Dataflow<T>, IBatchedDataflow where T : class
    {
        protected readonly TargetTable m_targetTable;
        protected readonly int m_bulkSize;
        protected readonly string m_dbBulkInserterName;
        protected readonly PostBulkInsertDelegate<T> m_postBulkInsert;
        protected readonly BatchBlock<T> m_batchBlock;
        protected readonly ActionBlock<T[]> m_actionBlock;

        public DbBulkInserter(
            string connectionString,
            string destTable,
            DataflowOptions options,
            string destLabel,
            int bulkSize = 4096 * 2,
            string dbBulkInserterName = null,
            PostBulkInsertDelegate<T> postBulkInsert = null)
            : this(new TargetTable(destLabel, connectionString, destTable), options, bulkSize, dbBulkInserterName, postBulkInsert)
        {
        }

        public DbBulkInserter(TargetTable targetTable, 
            DataflowOptions options, 
            int bulkSize = 4096 * 2, 
            string dbBulkInserterName = null,
            PostBulkInsertDelegate<T> postBulkInsert = null) 
            : base(options)
        {
            m_targetTable = targetTable;
            m_bulkSize = bulkSize;
            m_dbBulkInserterName = dbBulkInserterName;
            m_postBulkInsert = postBulkInsert;
            m_batchBlock = new BatchBlock<T>(bulkSize);
            m_actionBlock = new ActionBlock<T[]>(async array =>
            {
                LogHelper.Logger.Debug(h => h("{3} starts bulk-inserting {0} {1} to db table {2}", array.Length, typeof(T).Name, m_targetTable.TableName, this.FullName));
                await DumpToDB(array, targetTable);
                LogHelper.Logger.Info(h => h("{3} bulk-inserted {0} {1} to db table {2}", array.Length, typeof(T).Name, m_targetTable.TableName, this.FullName));
            });
            m_batchBlock.LinkTo(m_actionBlock, m_defaultLinkOption);

            RegisterChild(m_batchBlock);
            RegisterChild(m_actionBlock);
        }

        protected async virtual Task DumpToDB(T[] data, TargetTable targetTable)
        {
            using (var bulkReader = new BulkDataReader<T>(TypeAccessorManager<T>.GetAccessorForTable(targetTable), data))
            {
                using (var conn = new SqlConnection(targetTable.ConnectionString))
                {
                    await conn.OpenAsync();

                    var transaction = conn.BeginTransaction();
                    try
                    {
                        using (var bulkCopy = new SqlBulkCopy(conn, SqlBulkCopyOptions.TableLock, transaction))
                        {
                            foreach (SqlBulkCopyColumnMapping map in bulkReader.ColumnMappings)
                            {
                                bulkCopy.ColumnMappings.Add(map);
                            }

                            bulkCopy.DestinationTableName = targetTable.TableName;
                            bulkCopy.BulkCopyTimeout = (int)TimeSpan.FromMinutes(30).TotalMilliseconds;
                            bulkCopy.BatchSize = m_bulkSize;

                            // Write from the source to the destination.
                            await bulkCopy.WriteToServerAsync(bulkReader);
                        }
                    }
                    catch (Exception e)
                    {
                        if (e is NullReferenceException)
                        {
                            LogHelper.Logger.ErrorFormat(
                                "{0} NullReferenceException occurred in bulk insertion. This is probably caused by forgetting assigning value to a [NoNullCheck] attribute when constructing your object.", this.FullName);
                        }

                        LogHelper.Logger.ErrorFormat("{0} Bulk insertion failed. Rolling back all changes...", this.FullName, e);
                        transaction.Rollback();
                        LogHelper.Logger.InfoFormat("{0} Changes successfully rolled back", this.FullName);

                        //As this is an unrecoverable exception, rethrow it
                        throw;
                    }
                    
                    transaction.Commit();
                    await this.OnPostBulkInsert(conn, targetTable, data);
                }
            }
        }

        public override ITargetBlock<T> InputBlock { get { return m_batchBlock; } }
        
        public override string Name
        {
            get {
                return m_dbBulkInserterName ?? base.Name;
            }
        }

        public override Tuple<int, int> BufferStatus
        {
            get
            {
                var bs = base.BufferStatus;
                return new Tuple<int, int>(bs.Item1 * m_bulkSize, bs.Item2 * m_bulkSize);
            }
        }

        protected virtual async Task OnPostBulkInsert(SqlConnection sqlConnection, TargetTable target, T[] insertedData)
        {
            if (m_postBulkInsert != null)
            {
                await m_postBulkInsert(sqlConnection, m_targetTable, insertedData);
            }
        }

        public void TriggerBatch()
        {
            m_batchBlock.TriggerBatch();
        }
    }

    /// <summary>
    /// The handler which allows you to take control after a bulk insertion succeeds. (e.g. you may want to 
    /// execute a stored prodecure after every bulk insertion)
    /// </summary>
    /// <param name="connection">The connection used by previous bulk insert (already opened)</param>
    /// <param name="target">The destination table of the bulk insertion</param>
    /// <param name="insertedData">The inserted data of this round of bulk insertion</param>
    /// <returns>A task represents the state of the post bulk insert job (so you can use await in the delegate)</returns>
    public delegate Task PostBulkInsertDelegate<T>(SqlConnection connection, TargetTable target, ICollection<T> insertedData);
}
