using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;

namespace Gridsum.DataflowEx.Databases
{
    /// <summary>
    /// The class helps you to bulk insert parsed objects to multiple database tables (e.g. group by profileId)
    /// </summary>
    /// <typeparam name="T">The db-mapped type of parsed objects (usually generated by EF/linq2sql)</typeparam>
    public class MultiDbBulkInserter<T> : DataDispatcher<T, int> where T:class
    {
        private Func<int, string> m_connectionGetter;
        private string m_destTable;
        private readonly string m_destLabel;
        private DataflowOptions m_options;
        private int m_bulkSize;
        private readonly string m_displayName;
        private readonly PostBulkInsertDelegate m_postBulkInsert;

        public MultiDbBulkInserter(DataflowOptions options, 
            Func<T, int> dispatchFunc, 
            Func<int, string> connectionGetter, 
            string destTable, 
            string destLabel, 
            int bulkSize = 4096 * 2, 
            string displayName = null,
            PostBulkInsertDelegate postBulkInsert = null)
            : base(dispatchFunc)
        {
            m_options = options;
            m_connectionGetter = connectionGetter;
            m_destTable = destTable;
            m_destLabel = destLabel;
            m_bulkSize = bulkSize;
            m_displayName = displayName;
            this.m_postBulkInsert = postBulkInsert;
        }

        protected override Dataflow<T> CreateChildFlow(int dispatchKey)
        {
            return new DbBulkInserter<T>(
                this.m_connectionGetter(dispatchKey),
                this.m_destTable,
                this.m_options,
                this.m_destLabel,
                this.m_bulkSize,
                string.Format("childDbBulkInserter_{0}", dispatchKey),
                this.m_postBulkInsert);
        }
        
        public override string Name
        {
            get
            {
                return m_displayName ?? base.Name;
            }
        }
    }
}
